In [1]:
import numpy as np

1. Создать квадратную матрицу из случайных целых чисел из
[-5,5] размера 7. Создать две новые матрицы: первая – из трех последних строк исходной матрицы (должна получиться матрица
размера 3х7), вторая – из двух первых столбцов матрицы (матрица
размера 7х2). 

In [4]:
B = np.random.randint(-5, 5, (7, 7)) 
C = B[-3:, :]
M_ = B[:, :2]
print(B)
print(C)
print(M_)




[[ 2 -1 -4 -5  3  0  1]
 [ 3  1 -2 -5 -5  3  1]
 [-5 -1 -1  3  4 -1 -2]
 [ 3 -3  1 -3  1  3  3]
 [ 2  1  4 -2  0  2  1]
 [-1  2 -2  3 -1  4 -4]
 [ 0 -5  3  0 -3  2 -5]]
[[ 2  1  4 -2  0  2  1]
 [-1  2 -2  3 -1  4 -4]
 [ 0 -5  3  0 -3  2 -5]]
[[ 2 -1]
 [ 3  1]
 [-5 -1]
 [ 3 -3]
 [ 2  1]
 [-1  2]
 [ 0 -5]]


Выполнить умножение матриц из предыдущего пункта
тремя способами: используя векторный алгоритм умножения
матриц; используя матричный алгоритм, записав матрицу С по
строкам; проверив с помощью функции np.dot

In [10]:
#векторный
M = np.zeros((B.shape[0], C.shape[1]))
for i in range(len(B)):
    for j in range(len(C[0])):
        for p in range(len(C)):
            M[i][j] = M[i][j] + B[i][p] * C[p][j]
# Матричный алгоритм, записывая матрицу С по строкам (стандартное матричное умножение)
M_ = np.zeros((B.shape[0], C.shape[1]))
for i in range(B.shape[0]):
    for j in range(C.shape[1]):
        for k in range(B.shape[1]):
            M_[i, j] += B[i, k] * C[k, j]
B,C,M,M_,np.dot(B,C)

(array([[ 2,  1,  4, -2,  0,  2,  1],
        [-1,  2, -2,  3, -1,  4, -4],
        [ 0, -5,  3,  0, -3,  2, -5]]),
 array([[ 2, -1],
        [ 3,  1],
        [-5, -1],
        [ 3, -3],
        [ 2,  1],
        [-1,  2],
        [ 0, -5]]),
 array([[-21.,   0.],
        [ 17.,  23.],
        [-38.,  18.]]),
 array([[-21.,   0.],
        [ 17.,  23.],
        [-38.,  18.]]),
 array([[-21,   0],
        [ 17,  23],
        [-38,  18]]))

Создать вектор-строку 1x7 из случайных целых чисел. Вычислить норму ‖x‖3
 самостоятельно написанной функцией и
проверить результат с помощью linalg.norm().

In [20]:
vector = np.random.randint(1,9, (1, 7))[0] 
sum = 0.0
for i in vector:
    sum += abs(i)**3
sum=sum**(1/3)

sum,np.linalg.norm(vector, 3)

(7.553688825001928, 7.553688825001928)

Создать матрицу из случайных целых чисел. Найти норму
матрицы Фробениуса ‖A‖∞ с помощью самостоятельно
написанного алгоритма, проверить результат с помощью
linalg.norm().

In [16]:
matrix = np.random.randint(1, 11, size=(5, 5))
sum=0.0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[0]):
        sum+=matrix[i][j]**2

np.sqrt(sum),np.linalg.norm(matrix)

(29.647934160747187, 29.647934160747187)

In [17]:
v = vector.copy()
v[3-1:] = 0
# Вычисляем вектор отражения
v = v - np.linalg.norm(vector) * np.eye(len(vector))[:, 3-1]
v

array([  7.        ,   8.        , -15.06651917,   0.        ,
         0.        ,   0.        ,   0.        ])

Для матрицы, созданной в 4 пункте, найти LU разложение
самостоятельно написанной функцией и проверить результат с
помощью перемножения матриц.


In [22]:
L = np.eye(matrix.shape[0])  # Создаем начальную матрицу L как единичную
U = matrix.astype("float")  # Создаем копию исходной матрицы для U
for key in range(matrix.shape[0]):
    for i in range(key+1, matrix.shape[0]):
        factor = U[i, key] / U[key, key]
        L[i, key] = factor
        U[i, key:] -= factor * U[key, key:]

matrix, L, U,np.dot(L, U)




(array([[ 1,  3,  3,  5,  4],
        [10,  2,  5,  6,  4],
        [ 3,  6,  3,  6,  8],
        [ 3,  8,  9,  2,  6],
        [ 8,  6,  9, 10,  3]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [10.        ,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 3.        ,  0.10714286,  1.        ,  0.        ,  0.        ],
        [ 3.        ,  0.03571429, -0.2688172 ,  1.        ,  0.        ],
        [ 8.        ,  0.64285714, -0.32258065,  0.24615385,  1.        ]]),
 array([[ 1.00000000e+00,  3.00000000e+00,  3.00000000e+00,
          5.00000000e+00,  4.00000000e+00],
        [ 0.00000000e+00, -2.80000000e+01, -2.50000000e+01,
         -4.40000000e+01, -3.60000000e+01],
        [ 0.00000000e+00,  0.00000000e+00, -3.32142857e+00,
         -4.28571429e+00, -1.42857143e-01],
        [ 0.00000000e+00,  0.00000000e+00, -1.11022302e-16,
         -1.25806452e+01, -4.75268817e+00],
        [ 0.00000000e+00,  0.00000000e+00,  0.00000000e

Для матрицы, созданной в 4 пункте, найти QR разложение
всеми рассмотренными методами, проверить результат с помощью
перемножения матриц и с помощью функции np.linalg.q

In [30]:
#разложение методом Грама-Шмидта
copy =  matrix.astype("float") 
Q = np.zeros_like(copy)
count = 0
for a in copy.T:
    v = np.copy(a)
    for i in range(0,count):
        v -= np.dot(np.dot(Q[:, i].T, a), Q[:, i])
    e = v/np.linalg.norm(v)
    Q[:, count] = e
    count += 1
R = np.dot(Q.T, copy)

Q_np, R_np = np.linalg.qr(matrix)

matrix,"Q*R:", np.dot(Q, R),"Матрица Q (метод Грама-Шмидта): ", Q,"Матрица R (метод Грама-Шмидта): ", R,"Матрица Q (с использованием np.linalg.qr): ", Q_np,"Матрица R (с использованием np.linalg.qr): ", R_np

(array([[ 1,  3,  3,  5,  4],
        [10,  2,  5,  6,  4],
        [ 3,  6,  3,  6,  8],
        [ 3,  8,  9,  2,  6],
        [ 8,  6,  9, 10,  3]]),
 'Q*R:',
 array([[ 1.,  3.,  3.,  5.,  4.],
        [10.,  2.,  5.,  6.,  4.],
        [ 3.,  6.,  3.,  6.,  8.],
        [ 3.,  8.,  9.,  2.,  6.],
        [ 8.,  6.,  9., 10.,  3.]]),
 'Матрица Q (метод Грама-Шмидта): ',
 array([[ 0.07392213,  0.26767444,  0.0592616 ,  0.59815932,  0.74938602],
        [ 0.73922127, -0.4690442 , -0.12736528, -0.30764902,  0.35025651],
        [ 0.22176638,  0.46597453, -0.8455388 ,  0.01792242, -0.13575834],
        [ 0.22176638,  0.69067372,  0.40642137, -0.54002386,  0.130328  ],
        [ 0.59137702,  0.11910285,  0.31646793,  0.5055794 , -0.52945751]]),
 'Матрица R (метод Грама-Шмидта): ',
 array([[ 1.35277493e+01,  8.35320036e+00,  1.19014625e+01,
          1.24928395e+01,  8.13143398e+00],
        [ 6.66133815e-16,  8.90078894e+00,  7.14371500e+00,
          3.89233011e+00,  7.42366808e+00],
   