In [7]:
import numpy as np

1. Создать квадратную матрицу из случайных целых чисел из
[-5,5] размера 7. Создать две новые матрицы: первая – из трех последних строк исходной матрицы (должна получиться матрица
размера 3х7), вторая – из двух первых столбцов матрицы (матрица
размера 7х2). 

In [8]:
B = np.random.randint(-5, 5, (7, 7)) 
C = B[-3:, :]
M_ = B[:, :2]
print(B)
print(C)
print(M_)




[[-3  1 -5 -2 -2 -5 -4]
 [-4  3 -3  0 -5 -3  4]
 [ 3  2 -1 -5 -5  2  3]
 [-1  4 -3 -5  3 -4  0]
 [-5 -2  3 -2 -5  2  0]
 [ 4  2  4 -4  0  4 -2]
 [ 0 -1 -4  2 -4  1 -3]]
[[-5 -2  3 -2 -5  2  0]
 [ 4  2  4 -4  0  4 -2]
 [ 0 -1 -4  2 -4  1 -3]]
[[-3  1]
 [-4  3]
 [ 3  2]
 [-1  4]
 [-5 -2]
 [ 4  2]
 [ 0 -1]]


Выполнить умножение матриц из предыдущего пункта
тремя способами: используя векторный алгоритм умножения
матриц; используя матричный алгоритм, записав матрицу С по
строкам; проверив с помощью функции np.dot

In [9]:
#векторный
M = np.zeros((B.shape[0], C.shape[1]))
for i in range(len(B)):
    for j in range(len(C[0])):
        for p in range(len(C)):
            M[i][j] = M[i][j] + B[i][p] * C[p][j]
# Матричный алгоритм, записывая матрицу С по строкам (стандартное матричное умножение)
M_ = np.zeros((B.shape[0], C.shape[1]))
for i in range(B.shape[0]):
    for j in range(C.shape[1]):
        for k in range(B.shape[1]):
            M_[i, j] += B[i, k] * C[k, j]
B,C,M,M_,np.dot(B,C)

IndexError: index 3 is out of bounds for axis 0 with size 3

Создать вектор-строку 1x7 из случайных целых чисел. Вычислить норму ‖x‖3
 самостоятельно написанной функцией и
проверить результат с помощью linalg.norm().

In [12]:
vector = np.random.randint(1,9, (1, 7))[0] 
sum = 0.0
for i in vector:
    sum += abs(i)**3
sum=sum**(1/3)

sum,np.linalg.norm(vector, 3)

(9.35609523735209, 9.35609523735209)

Создать матрицу из случайных целых чисел. Найти норму
матрицы Фробениуса ‖A‖∞ с помощью самостоятельно
написанного алгоритма, проверить результат с помощью
linalg.norm().

In [10]:
matrix = np.random.randint(1, 11, size=(5, 5))
sum=0.0
for i in range(matrix.shape[0]):
    for j in range(matrix.shape[0]):
        sum+=matrix[i][j]**2

np.sqrt(sum),np.linalg.norm(matrix)

(31.51190251317746, 31.51190251317746)

In [13]:
v = vector.copy()
v[3-1:] = 0
# Вычисляем вектор отражения
v = v - np.linalg.norm(vector) * np.eye(len(vector))[:, 3-1]
v

array([  1.        ,   6.        , -11.87434209,   0.        ,
         0.        ,   0.        ,   0.        ])

Для матрицы, созданной в 4 пункте, найти LU разложение
самостоятельно написанной функцией и проверить результат с
помощью перемножения матриц.


In [14]:
L = np.eye(matrix.shape[0])  # Создаем начальную матрицу L как единичную
U = matrix.astype("float")  # Создаем копию исходной матрицы для U
for key in range(matrix.shape[0]):
    for i in range(key+1, matrix.shape[0]):
        factor = U[i, key] / U[key, key]
        L[i, key] = factor
        U[i, key:] -= factor * U[key, key:]

matrix, L, U,np.dot(L, U)




(array([[ 3,  6,  8,  2,  1],
        [ 8,  9,  7,  8,  4],
        [ 8,  1, 10,  6,  6],
        [ 5,  2,  6, 10,  5],
        [10,  1,  8,  3,  2]]),
 array([[ 1.        ,  0.        ,  0.        ,  0.        ,  0.        ],
        [ 2.66666667,  1.        ,  0.        ,  0.        ,  0.        ],
        [ 2.66666667,  2.14285714,  1.        ,  0.        ,  0.        ],
        [ 1.66666667,  1.14285714,  0.46683047,  1.        ,  0.        ],
        [ 3.33333333,  2.71428571,  1.04422604, -0.94284539,  1.        ]]),
 array([[  3.        ,   6.        ,   8.        ,   2.        ,
           1.        ],
        [  0.        ,  -7.        , -14.33333333,   2.66666667,
           1.33333333],
        [  0.        ,   0.        ,  19.38095238,  -5.04761905,
           0.47619048],
        [  0.        ,   0.        ,   0.        ,   5.97542998,
           1.58722359],
        [  0.        ,   0.        ,   0.        ,   0.        ,
          -3.953125  ]]),
 array([[ 3.,  6.,  8., 

Для матрицы, созданной в 4 пункте, найти QR разложение
всеми рассмотренными методами, проверить результат с помощью
перемножения матриц и с помощью функции np.linalg.q

In [17]:
#разложение методом Грама-Шмидта
copy =  matrix.astype("float") 
Q = np.zeros_like(copy)
count = 0
for a in copy.T:
    v = np.copy(a)
    for i in range(count):
        v -= np.dot(np.dot(Q[:, i].T, a), Q[:, i])
    e = v/np.linalg.norm(v)
    Q[:, count] = e
    count += 1
R = Q.T @ copy

Q_np, R_np = np.linalg.qr(matrix)

matrix,"Q*R:", np.dot(Q, R),"Матрица Q (метод Грама-Шмидта): ", Q,"Матрица R (метод Грама-Шмидта): ", R,"Матрица Q (с использованием np.linalg.qr): ", Q_np,"Матрица R (с использованием np.linalg.qr): ", R_np

(array([[ 3,  6,  8,  2,  1],
        [ 8,  9,  7,  8,  4],
        [ 8,  1, 10,  6,  6],
        [ 5,  2,  6, 10,  5],
        [10,  1,  8,  3,  2]]),
 'Q*R:',
 array([[ 3.,  6.,  8.,  2.,  1.],
        [ 8.,  9.,  7.,  8.,  4.],
        [ 8.,  1., 10.,  6.,  6.],
        [ 5.,  2.,  6., 10.,  5.],
        [10.,  1.,  8.,  3.,  2.]]),
 'Матрица Q (метод Грама-Шмидта): ',
 array([[ 0.18534062,  0.55622098,  0.6675169 , -0.34075354, -0.30753096],
        [ 0.49424165,  0.64572781, -0.50612235,  0.08309286,  0.27513004],
        [ 0.49424165, -0.31144722,  0.45734506,  0.05313573,  0.66838456],
        [ 0.30890103, -0.03014005,  0.1692586 ,  0.83353775, -0.42454454],
        [ 0.61780206, -0.41922074, -0.24586254, -0.42352568, -0.45028012]]),
 'Матрица R (метод Грама-Шмидта): ',
 array([[ 1.61864141e+01,  7.29006435e+00,  1.66806557e+01,
          1.22324809e+01,  7.90786641e+00],
        [ 2.22044605e-15,  8.35792808e+00,  2.32078410e+00,
          2.85051836e+00,  2.81307163e-01],
   